alsa-state: run alsactl store in pkg_postinst
Since the pkg_postinst is prior than alsa-state-init, it needs
to run store first. On some boards, it failed to online install
alsa-state

[dnf install alsa-state online]
root@bcm-2xxx-rpi4:~# # dnf install alsa-state
No state is present for card Headphones
alsa-lib ../../../alsa-lib-1.2.3.2/src/ucm/main.c:983:(snd_use_case_mgr_open)
error: failed to import hw:0 use case configuration -2
Found hardware: "bcm2835_headpho" "Broadcom Mixer" "" "" ""
Hardware is initialized using a generic method
No state is present for card Headphones
%post(alsa-state-0.2.0-r5.0.cortexa72): waitpid(823) rc 823 status 6300
warning: %post(alsa-state-0.2.0-r5.0.cortexa72) scriptlet failed, exit status 99

Error in POSTIN scriptlet in rpm package alsa-state
[dnf install alsa-state online]

Issue: LINCD-3051
(LOCAL REV: NOT UPSTREAM) -- Sent to upstream oe-core on 20200903

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>