libxcrypt.inc: use alternatives to resolve crypt.3 conflict
Issue: LIN1023-2865

To fix:

Error: Transaction test error:
  file /usr/share/man/man3/crypt.3 from install of
  libcrypt-doc-4.4.33-r0.x86_64 conflicts with file from package
  man-pages-6.04-r0.x86_64

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core on 20231205

Signed-off-by: Changqing Li <changqing.li@windriver.com>