qemu: Add qemu-user-* and qemu-system-* to PACKAGES_DYNAMIC
Issue: LINUXEXEC-27688

Fixes:
  Add below line to conf/local.conf
  IMAGE_INSTALL:append = " qemu-system-aarch64"
  $ bitbake core-image-base
  ERROR: Required build target 'core-image-base' has no buildable providers.
  Missing or unbuildable dependency chain was: ['core-image-base', 'qemu-system-aarch64']

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core 20230626

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>